### ISSUE TITLE
Multiple backends support

### ISSUE THREAD

**Issue by jrusnack** [jrusnack/xenuti#11]
Allow multiple backends. 

Also add new option to allow scripts choose which backends they`ll use and in which order, e.g.
```
process:
  flaws_sanity_check:
    args: -d 2010-01-01
    backends: flaws git
```

Now trouble comes when we would like to use multiple instances of git backend - to allow that new options `name` and `script` should be added to backends, so that they can be referred to by name from the script config.
